### ISSUE TITLE
64位加壳器打不开

### ISSUE THREAD

**Issue by zoubaba1997** [TimelifeCzy/Shell_Protect#1]

**Comment by zoubaba1997** [comment]
32位的用了之后程序不能运行

**Comment by zha0x1nsec** [comment]
缺的dll都下载了，x64文件夹下的程序还是打不开

**Comment by TimelifeCzy** [comment]
最近更新了下代码，后续没有Release版本了，但是x32/x64编译后加壳-脱壳流程都是没问题的。
加壳后不可以直接使用，只做学习和研究.，谢谢理解.
